version: '3'
services:
  jupyter:
    image: continuumio/anaconda3:latest
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/notebooks
    command: ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--allow-root"]

  spyder:
    image: compdatasci/spyder-desktop
    volumes:
      - .:/home/ubuntu/myproject

  mysql:
    image: mysql:latest
    volumes:
      - ./my/custom:/etc/mysql/conf.d
    environment:
      MYSQL_HOST: 
      MYSQL_USER: db_adic
      MYSQL_PASSWORD: password123
      MYSQL_ROOT_PASSWORD: sistemas123
      MYSQL_DATABASE: adic
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    #volumes:
    #  - /some/local/directory/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    environment:
      PMA_HOST: mysql
    ports:
      - "8080:80"
    depends_on:
      - mysql
